---
title: "Assignment1"
output: html_document
---

Gokce EZEROGLU,sales analyst at Avon Cosmetics. I have been working at business analysis department since 2017. My motivation for learning data science is to have broader understanding on deep dive analyses. Currently, programs like python, R, sql, are already being used in my team. Hopefully,  I will also be contributing to scientific based analyses at the end of this program.



1st Example:
I have watched '' the voice of R Community" over  the below link
https://www.youtube.com/watch?v=b_wOnvS1WcA
It  explains the mission of R Consortium, and shares  brief info about the usage of R all over  the world. 
For example
*Age, gender distribution of R users; Why do people use R in workplaces;size of data, being used in R.. and etc.

2nd Example:
2nd example was: Tree-Based Machine Learning for Insurance Pricing.. My industry is not linked to insurance. However,  the video was quite inspiring about developping of tariff plans based on the severity and frequency of claims.

3rd Example:
R-package for simulating linear model data (simrel)
 The properties of the linear relation between predictors and responses are defined by a small set of input parameters which allow versatile and adjustable simulations.





